server { # Bắt đầu một khối cấu hình định nghĩa một máy chủ ảo (Virtual Server)
    listen 80; # Thiết lập máy chủ lắng nghe các kết nối đến thông qua cổng 80 (cổng HTTP mặc định)
    location / { # Cấu hình các thiết lập cho tất cả các yêu cầu bắt đầu bằng đường dẫn gốc (/)
        root /usr/share/nginx/html; # Chỉ định thư mục gốc chứa các tệp tin web tĩnh trên ổ đĩa của container
        index index.html; # Xác định tệp tin mặc định sẽ được trả về nếu người dùng không chỉ định tệp cụ thể
        # Kiểm tra sự tồn tại của tệp theo thứ tự: tệp tin ($uri) -> thư mục ($uri/) -> nếu không thấy thì trả về index.html
        # Dòng này rất quan trọng để tránh lỗi 404 khi người dùng tải lại trang (refresh) ở các đường dẫn của ứng dụng SPA
        try_files $uri $uri/ /index.html; 
    }
}
